version: "1.0"
stages:
  - "clone"
  - "build"
  - "install"
  - "test"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "josuecodjo/mochachai"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "josuecodjo/mochachai"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile:
      content: "FROM node:8.16.0-alpine\n          WORKDIR /root/onboarding\n          COPY . /root/onboarding\n          RUN npm install\n	RUN npm test"
    stage: "build"