# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            node-version: [8.6]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with: 
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm install
    # How to pass artifacts between project --> Upload artifact
        - name: Download node-modules
          uses: actions/upload-artifact@v3
          with:
            name: my-node-modules
            path: node_modules
            retention-days: 1

  Test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy: 
      matrix:
          node-version: [8.6]
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with: 
            node-version: ${{ matrix.node-version }}
    # How to pass artifacts between project --> Download artifact
        - name: Download node-modules
          uses: actions/download-artifact@v3
          with:
            name: my-node-modules

        - name: Run test
          run: npm test